### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Hongbosherlock** [DawnMagnet/algorithm-station#1]
你好，请问你需要paddlepaddle开发组队吗

**Comment by DawnMagnet** [comment]
我这边是一个人，欢迎组队，我的微信DawnMagnet



---Original---
From: "Xu ***@***.***&gt;
Sent at: 2023年2月22日(Wed) Evening11:03
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [DawnMagnet/algorithm-station] paddlepaddle开发组队 (Issue #1)




 
你好，看到你也准备参加任务18，你们几个人了，要一起组队吗
